apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-app-secret
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "github-app-secret"
          containers:
            - name: github-app-secret
              image: ghcr.io/kingdon-ci/github-app-secret
              imagePullPolicy: IfNotPresent
              args:
                - "-v=3"
                - --privateKeyPath=/etc/secret-volume/privatekey.pem
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              securityContext:
                allowPrivilegeEscalation: false
              volumeMounts:
                - mountPath: /etc/secret-volume
                  name: secret-volume
          restartPolicy: OnFailure
          volumes:
            - name: secret-volume
              secret:
                secretName: github-app-private-key
