apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rbac.yaml
- cronjob.yaml
images:
- name: ghcr.io/kingdon-ci/github-app-secret
  newName: ghcr.io/fluxcd-community/github-app-secret
  newTag: rc-233ff9af
