name: build

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: make tidy && make build
      - name: Test
        run: make test

  ko-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ko.local
      - name: Build
        run: make ko-build
